### ISSUE TITLE
Can't solve SecurityError

### ISSUE THREAD

**Issue by ybelenko** [redannick/FlashSocket.IO#5]
Hi, there!
Can somebody provide example of sending policy file from the server side? I'm not asking for full implementation, just basic few lines on Node.js for instance. This SecurityError driving me nuts.

My crossdomain.xml looks like this:

```
<cross-domain-policy>
<allow-access-from domain="*" to-ports="*"/>
</cross-domain-policy>
```

And it placed at http://4r5.ru:843/crossdomain.xml

And here is my FlashSocket declaration:
`var socket:FlashSocket = new FlashSocket('http://4r5.ru:843');`

What's wrong with that?

**Comment by redannick** [comment]
Hi there, my apologies, but It's so long since I used socket.io from flash that I really can't remember much here. Looking back into some (very) old code suggests I was responding from the socket server with the policy file directly:

``` javascript
net = require('net');


function policy() {
  var xml = '<?xml version="1.0"?>\n<!DOCTYPE cross-domain-policy SYSTEM'
  + ' "http://www.macromedia.com/xml/dtds/cross-domain-policy.dtd">\n<cross-domain-policy>\n';
  xml += '<allow-access-from domain="*" to-ports="*"/>\n';
  xml += '</cross-domain-policy>\n';

  return xml;
}

// Start the server TCP
var screenserver = net.createServer(function (socket) 
{
    socket.setEncoding('utf8');
    socket.setKeepAlive(true, 10000);
    socket.write(policy() + '\0');
        // ....
}
```

@chatziko has been working on his fork more recently, perhaps he can help you out more

**Comment by chatziko** [comment]
Hello, use [my fork](https://github.com/chatziko/FlashPolicyFileServer) (contains some fixes) of FlashPolicyFileServer and try this (need to run as root):

```
const http = require('http')
const policyfile = require('policyfile')

const masterHttp = http.Server()
masterHttp.listen(80)

policyfile.createServer().listen(843, masterHttp)
```

It serves the policy file on both 843 and 80, in case 843 is not accessible but the user. Note that you need to serve the html page where the swf is from a web server, or if you run it locally you need to set the swf as trusted in the global security settings.

Works also with https.

If you want to connect with both http and https to the same server, you need to do it like this:

```
policyfile.createServer(null, ['*:80']).listen(843, masterHttp)
policyfile.createServer(null, ['*:443']).listen(-1, masterHttps)
```

(the policy file served on port 80 needs to allow only access on port 80, so that flash retrieves a new policty file via the TLS connection in port 443).

**Comment by ybelenko** [comment]
Thanks @chatziko, thanks @redannick 
I din't even expected so much help in such short time!
I've checked already this script on server and everything looks perfect so far.
